document.getElementById('circle2').addEventListener('mouseover', function(){
    TweenMax.to('#circle2', 0.5, { scale: 1.3})
})

document.getElementById('circle2').addEventListener('mouseout', function(){
    TweenMax.to('#circle2', 0.3, { scale: 1})
})


document.getElementById('circle2').addEventListener('click', function(){
    TweenMax.to('#circle2', 1.5, { scale: 7, ease: Power3.easeOut})
    TweenMax.to('#hi', 0.15, { opacity:0})
    TweenMax.to('#hi', 0.15, { display:'none'})
    TweenMax.to('#container', 0, { delay: 0.5, backgroundColor:'black'})
    TweenMax.to('.name', 0, { delay: 2, display: 'none'})
    TweenMax.to('#projects', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#archives', 0, { delay: 0.35, display:'none'})
    // TweenMax.to('#projects', 0, { delay: 0.35, color:'white'})
    // TweenMax.to('#archives', 0, { delay: 0.35, color:'white'})
    TweenMax.to('#contact', 0, { delay: 0.35, color:'white'})
    TweenMax.to('#contact',0, {delay: .35,display:'none'})
    TweenMax.to('#contact2',0, {delay: .35, display:'block'})
    TweenMax.to('#projects2',0, {display:'none'})
    TweenMax.to('#archives2',0, {display:'none'})
    TweenMax.to('#contact2',0, {color:'white'})
    TweenMax.to('#hi2', 0, { delay: 0.1, display:'block'})
    // TweenMax.to('#contact', 0, { delay: 0.35, display: 'none'})
    TweenMax.to('#email', 0, { display:'block'})
    TweenMax.to('#contactava', 0, { delay: 0.2, display:'block'})
    TweenMax.to('#circle2', 0, {delay: 2, display: 'none'})    
    TweenMax.to('#shortname', 0, {display:'block'})
    TweenMax.to('#shortname', 0, {color:'white'})
    TweenMax.to('.ellipse', 0, {display:'none'})

})

document.getElementById('contact').addEventListener('click', function(){
    TweenMax.to('#circle2', 1.5, { scale: 7, ease: Power3.easeOut})
    TweenMax.to('#hi', 0.15, { opacity:0})
    TweenMax.to('#hi', 0.15, { display:'none'})
    TweenMax.to('#circle2', 0, { delay: 1, display:'none'})
    TweenMax.to('#container', 0, { delay: 0.5, backgroundColor:'black'})
    TweenMax.to('.name', 0, { delay: 2, display: 'none'})
    TweenMax.to('#projects', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#archives', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#hi2', 0, { delay: 0.1, display:'block'})
    TweenMax.to('#email', 0, { delay: 0.1, display:'block'})
    TweenMax.to('#contactava', 1, { delay: 0.2, display:'block'})
    TweenMax.to('#circle2', 0, {delay: 1, display:'none'})
    TweenMax.to('#shortname', 0, {display:'block'})
    TweenMax.to('#shortname', 0, {color:'white'})
    TweenMax.to('.ellipse', 0, {display:'none'})
    TweenMax.to('#contact2',0, {delay: .35, display:'block'})
    TweenMax.to('#contact2',0, {color:'white'})
    TweenMax.to('#tspan', 0.3, { opacity: 0})
})

document.getElementById('shortname').addEventListener('click', function(){
    TweenMax.to('#email', 0, { delay: .5, display:'none'})
    TweenMax.to('#contactava', 0, {delay: .5, display:'none'})
    TweenMax.to('#hi2', 0, {delay: .5,display:'none'})
    TweenMax.to('#shortname', 0, {delay: .5, display:'none'})
    TweenMax.to('.projectsname', 0, {delay: .5, display:'none'})
    TweenMax.to('#circle2', 0, {scale:7})
    TweenMax.to('#container', 0, {backgroundColor:'white'})
    TweenMax.to('#circle2', 0, {display: 'block'})
    TweenMax.to('#circle2', 1, {scale:1, ease: Power3.easeIn, transform: 'translate(-50%)' })
    TweenMax.to('.name', 0, { delay: 0.5, display: 'block'})
    TweenMax.to('#projects', 0, { delay: 0.5, display:'block'})
    TweenMax.to('#projects', 0, { color:'black'})
    TweenMax.to('#projects2',0, { delay: 0.5,display:'none'})
    TweenMax.to('#archives', 0, { delay: 0.5, display:'block'})
    TweenMax.to('#archives', 0, { color:'black'})
    TweenMax.to('#archives2',0, { delay: 0.5,display:'none'})
    TweenMax.to('#contact', 0, { delay: 0.5, display:'block'})
    TweenMax.to('#contact', 0, { color:'black'})
    TweenMax.to('#contact2',0, { delay: 0.5,display:'none'})
    TweenMax.to('#hi', 0.1, {opacity: 0})
    TweenMax.to('#hi', 0, { delay: 0.5, display:'block'})
    TweenMax.to('#hi', 1, { delay:.5, opacity:1})
    TweenMax.to('.name', 1, {opacity:1})
    TweenMax.to('#circle2', 1, {opacity:1})
    TweenMax.to('#filmscroll', 0, {delay: .5, display:'none'})
    TweenMax.to('#agtscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('.apcprojects', 1, { opacity: 0})
    TweenMax.to ('.apcprojects', 0, { delay: 1, display:'none'})
    TweenMax.to('#tanscroll', .5, { opacity:0})
    TweenMax.to('#tanscroll', 0, { delay:.5, display:'none'})
    TweenMax.to('#cleansedscroll', .5, { opacity:0})
    TweenMax.to('#cleansedscroll', 0, { delay:.5, display:'none'})
    TweenMax.to('#homesickscroll', .5, { opacity:0})
    TweenMax.to('#homesickscroll', 0, { delay:.5, display:'none'})
    TweenMax.to('#slothscroll', .5, { opacity:0})
    TweenMax.to('#slothscroll', 0, { delay:.5, display:'none'})
    TweenMax.to('#theofficeplaygroundscroll', .5, { opacity:0})
    TweenMax.to('#theofficeplaygroundscroll', 0, { delay:.5, display:'none'})
    TweenMax.to('#abysmscroll', .5, { opacity:0})
    TweenMax.to('#abysmscroll', 0, { delay:.5, display:'none'})
    TweenMax.to('#prevcontainer', .5, { opacity:0})
    TweenMax.to('#prevcontainer', 0, { delay:.5, display:'none'})
})

document.getElementById('contact').addEventListener('mouseover', function(){
    TweenMax.to('#ellipse1', 0, { display:'block'})
    TweenMax.to('#ellipse1', .5, { backgroundColor:'black'})
    TweenMax.to('#contact', .5, { color:'white'})
    TweenMax.to('#contact', .2, { scale:.9})
})

document.getElementById('contact').addEventListener('mouseout', function(){
    TweenMax.to('#ellipse1', 0, { display:'none'})
    // TweenMax.to('#ellipse1', .5, { backgroundColor:'white'})
    TweenMax.to('#contact', .5, { color:'black'})
    TweenMax.to('#contact', .2, { scale:1})
})

document.getElementById('projects').addEventListener('mouseover', function(){
    TweenMax.to('#ellipse2', 0, { display:'block'})
    TweenMax.to('#ellipse2', .5, { backgroundColor:'black'})
    TweenMax.to('#projects', .5, { color:'white'})
    TweenMax.to('#projects', .2, { scale:.9})
})

document.getElementById('projects').addEventListener('mouseout', function(){
    TweenMax.to('#ellipse2', 0, { display:'none'})
    // TweenMax.to('#ellipse2', .5, { backgroundColor:'white'})
    TweenMax.to('#projects', .5, { color:'black'})
    TweenMax.to('#projects', .2, { scale:1})
})
document.getElementById('archives').addEventListener('mouseover', function(){
    TweenMax.to('#ellipse3', 0, { display:'block'})
    TweenMax.to('#ellipse3', .5, { backgroundColor:'black'})
    TweenMax.to('#archives', .5, { color:'white'})
    TweenMax.to('#archives', .2, { scale:.9})
 })
    
document.getElementById('archives').addEventListener('mouseout', function(){
    TweenMax.to('#ellipse3', 0, { display:'none'})
    // TweenMax.to('#ellipse3', .5, { backgroundColor:'white'})
    TweenMax.to('#archives', .5, { color:'black'})
    TweenMax.to('#archives', .2, { scale:1})
})

document.getElementById('projects').addEventListener('click', function(){
    TweenMax.to('#circle2', 1.5, { scale: 7, ease: Power3.easeOut})
    TweenMax.to('#hi', 0.15, { opacity:0})
    TweenMax.to('#hi', 0.15, { display:'none'})
    TweenMax.to('#circle2', 0, { delay: 1, display:'none'})
    TweenMax.to('#container', 0, { delay: 0.5, backgroundColor:'black'})
    TweenMax.to('.name', 0, { delay: 1, display: 'none'})
    TweenMax.to('#projects2', 0, { display:'block'})
    TweenMax.to('#projects2', 0, { color:'white'})
    TweenMax.to('#archives', 0, { delay: 0.35, color:'white'})
    TweenMax.to('#contact', 0, { delay: 0.35, color:'white'})
    // TweenMax.to('#contact', 0, { delay: 0.35, display: 'none'})
    TweenMax.to('#circle2', 0, {delay: 1, display: 'none'})    
    TweenMax.to('#shortname', 0, {display:'block'})
    TweenMax.to('#shortname', 0, {color:'white'})
    TweenMax.to('.projectsname', .1 ,{ display: 'block'})
    TweenMax.to('.projectsname', .1 ,{ opacity:'100'})
    TweenMax.to('#contact', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#archives', 0, { delay: 0.35, display:'none'})
    TweenMax.to('.ellipse', 0, {display:'none'})
    TweenMax.to('.rectangles', 0 ,{ display: 'block'})
    TweenMax.to('#rectangleapc', 0, {transformOrigin:'top' })
    TweenMax.to('#rectangleagt', 0, {transformOrigin:'top' })
    TweenMax.to('#rectanglefilm', 0, {transformOrigin:'top' })
    TweenMax.to('#rectangleglams', 0, {transformOrigin:'top' })
    TweenMax.to('#rectangleothers', 0, {transformOrigin:'top' })
    TweenMax.to('.slider-container', .35 ,{ opacity: 0})
    TweenMax.to('.slider-container', 0 ,{ delay: .35, display: 'none'})
    TweenMax.to ('.apcprojects', .35, {opacity: 0})
    TweenMax.to ('.apcprojects', 0, {delay: .35, display:'none'})
    TweenMax.to ('#filmscroll', .5, {opacity: 0})
    TweenMax.to ('#filmscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#agtscroll', .5, {opacity: 0})
    TweenMax.to ('#agtscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#tanscroll', .5, {opacity: 0})
    TweenMax.to ('#tanscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#cleansedscroll', .5, {opacity: 0})
    TweenMax.to ('#cleansedscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#homesickscroll', .5, {opacity: 0})
    TweenMax.to ('#homesickscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#slothscroll', .5, {opacity: 0})
    TweenMax.to ('#slothscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#theofficeplaygroundscroll', .5, {opacity: 0})
    TweenMax.to ('#theofficeplaygroundscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#abysmscroll', .5, {opacity: 0})
    TweenMax.to ('#abysmscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#prevcontainer', .5, {opacity: 0})
    TweenMax.to ('#prevcontainer', 0, {delay: .5, display:'none'})
})

document.getElementById('apc').addEventListener('mouseover', function(){
    TweenMax.to('#rectangleapc', .5, { scaleY: 1 })
    TweenMax.to('#rectangleapc', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#apc', 0, { color:'black'})
})

document.getElementById('apc').addEventListener('mouseout', function(){
    TweenMax.to('#rectangleapc', 0.5, {scaleY: 0})
    TweenMax.to('#rectangleapc', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#apc', 0, {color: 'white'})
})

document.getElementById('agt').addEventListener('mouseover', function(){
    TweenMax.to('#rectangleagt', .5, { scaleY: 1 })
    TweenMax.to('#rectangleagt', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#agt', 0, { color:'black'})
})

document.getElementById('agt').addEventListener('mouseout', function(){
    TweenMax.to('#rectangleagt', 0.5, {scaleY: 0})
    TweenMax.to('#rectangleagt', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#agt', 0, {color: 'white'})
})
document.getElementById('film').addEventListener('mouseover', function(){
    TweenMax.to('#rectanglefilm', .5, { scaleY: 1 })
    TweenMax.to('#rectanglefilm', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#film', 0, { color:'black'})
})

document.getElementById('film').addEventListener('mouseout', function(){
    TweenMax.to('#rectanglefilm', 0.5, {scaleY: 0})
    TweenMax.to('#rectanglefilm', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#film', 0, {color: 'white'})
})

document.getElementById('glams').addEventListener('mouseover', function(){
    TweenMax.to('#rectangleglams', .5, { scaleY: 1 })
    TweenMax.to('#rectangleglams', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#glams', 0, { color:'black'})
})

document.getElementById('glams').addEventListener('mouseout', function(){
    TweenMax.to('#rectangleglams', 0.5, {scaleY: 0})
    TweenMax.to('#rectangleglams', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#glams', 0, {color: 'white'})
})

document.getElementById('others').addEventListener('mouseover', function(){
    TweenMax.to('#rectangleothers', .5, { scaleY: 1 })
    TweenMax.to('#rectangleothers', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#others', 0, { color:'black'})
})

document.getElementById('others').addEventListener('mouseout', function(){
    TweenMax.to('#rectangleothers', 0.5, {scaleY: 0})
    TweenMax.to('#rectangleothers', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#others', 0, {color: 'white'})
})

document.getElementById('apc').addEventListener('click', function(){
    TweenMax.to('#rectangleapc', 1, {transformOrigin:'center' })
    TweenMax.to('#rectangleapc', 2, {scaleX: 6})
    TweenMax.to('#rectangleapc', .5, {scaleY: 15})
    TweenMax.to('.rectangles', 0, {delay: .75, display:'none'})
    TweenMax.to('#container', 0, { delay: .75, backgroundColor:'white'})  
    TweenMax.to('#shortname', 0, {color: 'black'})
    TweenMax.to('#apc', 2 ,{ display: 'none'})
    TweenMax.to('#apc', 1 ,{ opacity: 0})
    TweenMax.to('#agt', 1 ,{ display: 'none'})
    TweenMax.to('#glams', 1 ,{ display: 'none'})
    TweenMax.to('#film', 1 ,{ display: 'none'})
    TweenMax.to('#others', 1 ,{ display: 'none'})
    TweenMax.to('#projects', 0, {delay: .25, display:'block'})
    TweenMax.to('#projects2', 0, {delay: .25, display:'none'})
    TweenMax.to ('.apcprojects', 0, {delay: .75, display:'block'})
    TweenMax.to('#tancover', 0.25, {opacity:1})
    TweenMax.to('#homesickcover', 0.25, {opacity:1})
    TweenMax.to('#abysmcover', 0.25, {opacity:1})
    TweenMax.to('#slothcover', 0.25, {opacity:1})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:1})
    TweenMax.to('#cleansedcover', 0.25, {opacity:1})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'block'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'block'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'block'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'block'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'block'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'block'})
    TweenMax.to('#tanscroll', 0, {delay: .25, display: 'none'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:1})
    TweenMax.to('#homesickname', 0.25, {opacity:1})
    TweenMax.to('#abysmname', 0.25, {opacity:1})
    TweenMax.to('#slothname', 0.25, {opacity:1})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:1})
    TweenMax.to('#cleansedname', 0.25, {opacity:1})
    TweenMax.to('#tanname', 0, { delay:.25, display:'block'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'block'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'block'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'block'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'block'})
    TweenMax.to ('.apcprojects', 1, {delay: .75, opacity: 1})
})
document.getElementById('film').addEventListener('click', function(){
    TweenMax.to('#filmscroll', .35 ,{ delay: .45, opacity: 1})
    TweenMax.to('#filmscroll', 0 ,{ delay: .45,display: 'block'})
    TweenMax.to('#rectanglefilm', 1, {transformOrigin:'center' })
    TweenMax.to('#rectanglefilm', 2, {scaleX: 6})
    TweenMax.to('#rectanglefilm', .5, {scaleY: 15})
    TweenMax.to('.rectangles', 0, {delay: .75, display:'none'})
    TweenMax.to('#container', 0, { delay: .5, backgroundColor:'white'})  
    TweenMax.to('#shortname', 0, {color: 'black'})
    TweenMax.to('#apc', 1 ,{ display: 'none'})
    TweenMax.to('#agt', .5 ,{ display: 'none'})
    TweenMax.to('#glams', .5 ,{ display: 'none'})
    TweenMax.to('#film', .5 ,{ display: 'none'})
    TweenMax.to('#others', .5 ,{ display: 'none'})
    TweenMax.to('.slider-container', .35 ,{ delay: .45, opacity: 1})
    TweenMax.to('.slider-container', 0 ,{ delay: .45, display: 'block'})
    TweenMax.to('#filmscroll', 0, {delay: .45, display:'block'})
    TweenMax.to('#projects', 0, {delay: .25, display:'block'})
    TweenMax.to('#projects2', 0, {delay: .25, display:'none'})
})

document.getElementById('archives').addEventListener('click', function(){
    TweenMax.to('#circle2', 1.5, { scale: 7, ease: Power3.easeOut})
    TweenMax.to('#hi', 0.5, { opacity:0})
    TweenMax.to('#hi', 0.5, { display:'none'})
    TweenMax.to('#circle2', 0, { delay: 1, display:'none'})
    TweenMax.to('#container', 0, { delay: 0.5, backgroundColor:'black'})
    TweenMax.to('.name', 0, { delay: 2, display: 'none'})
    TweenMax.to('#projects', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#contact', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#archives2', 0, { display:'block'})
    TweenMax.to('#archives2', 0, { color:'white'})
    TweenMax.to('#circle2', 0, {delay: 1, display:'none'})
    TweenMax.to('#shortname', 0, {display:'block'})
    TweenMax.to('#shortname', 0, {color:'white'})
    TweenMax.to('.ellipse', 0, {display:'none'})
    TweenMax.to('#filmscroll', 0, {delay: 1, display:'none'})
})

document.getElementById('tancover').addEventListener('mouseover', function (){
    TweenMax.to('#tanname', 0.25, {color:'white'})
    TweenMax.to('#container', 0.25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('tancover').addEventListener('mouseout', function (){
    TweenMax.to('#tanname', 0.25, {color:'black'})
    TweenMax.to('#container', 0.25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('cleansedcover').addEventListener('mouseover', function (){
    TweenMax.to('#cleansedname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('cleansedcover').addEventListener('mouseout', function (){
    TweenMax.to('#cleansedname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('slothcover').addEventListener('mouseover', function (){
    TweenMax.to('#slothname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('slothcover').addEventListener('mouseout', function (){
    TweenMax.to('#slothname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})
document.getElementById('abysmcover').addEventListener('mouseover', function (){
    TweenMax.to('#abysmname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('abysmcover').addEventListener('mouseout', function (){
    TweenMax.to('#abysmname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('theofficeplaygroundcover').addEventListener('mouseover', function (){
    TweenMax.to('#theofficeplaygroundname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('theofficeplaygroundcover').addEventListener('mouseout', function (){
    TweenMax.to('#theofficeplaygroundname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('homesickcover').addEventListener('mouseover', function (){
    TweenMax.to('#homesickname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('homesickcover').addEventListener('mouseout', function (){
    TweenMax.to('#homesickname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('tanname').addEventListener('mouseover', function (){
    TweenMax.to('#tanname', .25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('tanname').addEventListener('mouseout', function (){
    TweenMax.to('#tanname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('cleansedname').addEventListener('mouseover', function (){
    TweenMax.to('#cleansedname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('cleansedname').addEventListener('mouseout', function (){
    TweenMax.to('#cleansedname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('slothname').addEventListener('mouseover', function (){
    TweenMax.to('#slothname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('slothname').addEventListener('mouseout', function (){
    TweenMax.to('#slothname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})
document.getElementById('abysmname').addEventListener('mouseover', function (){
    TweenMax.to('#abysmname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('abysmname').addEventListener('mouseout', function (){
    TweenMax.to('#abysmname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('theofficeplaygroundname').addEventListener('mouseover', function (){
    TweenMax.to('#theofficeplaygroundname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('theofficeplaygroundname').addEventListener('mouseout', function (){
    TweenMax.to('#theofficeplaygroundname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('homesickname').addEventListener('mouseover', function (){
    TweenMax.to('#homesickname', 0.25, {color:'white'})
    TweenMax.to('#container', .25, {backgroundColor:'black'})
    // TweenMax.to('#shortname', 0.25, { color:'white'})
    // TweenMax.to('#projects', 0.25, { color:'white'})
})

document.getElementById('homesickname').addEventListener('mouseout', function (){
    TweenMax.to('#homesickname', 0.25, {color:'black'})
    TweenMax.to('#container', .25, {backgroundColor:'white'})
    // TweenMax.to('#shortname', 0.25, { color:'black'})
    // TweenMax.to('#projects', 0.25, { color:'black'})
})

document.getElementById('tancover').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#tanscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#tanscroll', .35, {opacity: 1})
    TweenMax.to ('#tanscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'})  
})

document.getElementById('tanname').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#tanscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#tanscroll', .35, {opacity: 1})
    TweenMax.to ('#tanscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prev', .35, {opacity: 1})
    TweenMax.to ('#prev', 0, { display:'block'})  
})

document.getElementById('tanname2').addEventListener('mouseover', function (){
    TweenMax.to('#tanname3', 0.25, { opacity:1})
    TweenMax.to('#tandefinition', 0.25, { opacity:1})
})

document.getElementById('cleansedcover').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#cleansedscroll', .35, {opacity: 1})
    TweenMax.to ('#cleansedscroll', 0, {delay: .35, display:'block'})
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'})   
})

document.getElementById('cleansedname').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#cleansedscroll', .35, {opacity: 1})
    TweenMax.to ('#cleansedscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'}) 
})

document.getElementById('homesickcover').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#homesickscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#homesickscroll', .35, {opacity: 1})
    TweenMax.to ('#homesickscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'}) 
})

document.getElementById('homesickname').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#homesickscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#homesickscroll', .35, {opacity: 1})
    TweenMax.to ('#homesickscroll', 0, {delay: .35, display:'block'}) 
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'})  
})

document.getElementById('slothname').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#slothscroll', .35, {opacity: 1})
    TweenMax.to ('#slothscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'}) 
})

document.getElementById('slothcover').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#slothscroll', .35, {opacity: 1})
    TweenMax.to ('#slothscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'}) 
})

document.getElementById('theofficeplaygroundname').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#theofficeplaygroundscroll', .35, {opacity: 1})
    TweenMax.to ('#theofficeplaygroundscroll', 0, {delay: .35, display:'block'}) 
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'})  
})

document.getElementById('theofficeplaygroundcover').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#theofficeplaygroundscroll', .35, {opacity: 1})
    TweenMax.to ('#theofficeplaygroundscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'}) 
})

document.getElementById('abysmname').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#abysmscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#abysmscroll', .35, {opacity: 1})
    TweenMax.to ('#abysmscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'}) 
})

document.getElementById('abysmcover').addEventListener('click', function (){
    TweenMax.to('#tancover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0.25, {opacity:0})
    TweenMax.to('#abysmcover', 0.25, {opacity:0})
    TweenMax.to('#slothcover', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundcover', 0.25, {opacity:0})
    TweenMax.to('#cleansedcover', 0.25, {opacity:0})
    TweenMax.to('#homesickcover', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancover', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#cleansedcover', 0, {delay:.25, display:'none'})
    TweenMax.to('#abysmscroll', 0, {delay: .25, display: 'block'})
    TweenMax.to('#container', .25, { backgroundColor: 'black'})
    TweenMax.to('#tanname', 0.25, {opacity:0})
    TweenMax.to('#homesickname', 0.25, {opacity:0})
    TweenMax.to('#abysmname', 0.25, {opacity:0})
    TweenMax.to('#slothname', 0.25, {opacity:0})
    TweenMax.to('#theofficeplaygroundname', 0.25, {opacity:0})
    TweenMax.to('#cleansedname', 0.25, {opacity:0})
    TweenMax.to('#tanname', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickname', 0, { delay:.25, display:'none'})
    TweenMax.to('#abysmname', 0, {delay:.25, display:'none'})
    TweenMax.to('#slothname', 0, {delay:.25, display:'none'})
    TweenMax.to('#theofficeplaygroundname', 0, {delay:.25, display:'none'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
    TweenMax.to ('#abysmscroll', .35, {opacity: 1})
    TweenMax.to ('#abysmscroll', 0, {delay: .35, display:'block'})  
    TweenMax.to ('#prevcontainer', .35, {opacity: 1})
    TweenMax.to ('#prevcontainer', 0, {delay: .35, display:'block'}) 
})

document.getElementById('prev').addEventListener('mouseover', function (){
    TweenMax.to('#prev path', 0.25, {fill:'white'})
})

document.getElementById('prev').addEventListener('mouseout', function (){
    TweenMax.to('#prev path', 0.25, {fill:'black'})
})

document.getElementById('prev').addEventListener('click', function (){
    TweenMax.to ('#tanscroll', .5, {opacity: 0})
    TweenMax.to ('#tanscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#cleansedscroll', .5, {opacity: 0})
    TweenMax.to ('#cleansedscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#homesickscroll', .5, {opacity: 0})
    TweenMax.to ('#homesickscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#slothscroll', .5, {opacity: 0})
    TweenMax.to ('#slothscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#theofficeplaygroundscroll', .5, {opacity: 0})
    TweenMax.to ('#theofficeplaygroundscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#abysmscroll', .5, {opacity: 0})
    TweenMax.to ('#abysmscroll', 0, {delay: .5, display:'none'})
    TweenMax.to ('#prevcontainer', .5, {opacity: 0})
    TweenMax.to ('#prevcontainer', 0, {delay: .5, display:'none'})
    TweenMax.to ('#tancover', .5, {delay:.5, opacity:1})
    TweenMax.to ('#tancover', 0, {delay:.5,display:'block'})
    TweenMax.to ('#tanname', .5, {delay:.5, opacity:1})
    TweenMax.to ('#tanname', 0, {delay:.5,display:'block'})
    TweenMax.to ('#cleansedcover', .5, {delay:.5, opacity:1})
    TweenMax.to ('#cleansedcover', 0, {delay:.5,display:'block'})
    TweenMax.to ('#cleansedname', .5, {delay:.5, opacity:1})
    TweenMax.to ('#cleansedname', 0, {delay:.5,display:'block'})
    TweenMax.to ('#theofficeplaygroundcover', .5, {delay:.5, opacity:1})
    TweenMax.to ('#theofficeplaygroundcover', 0, {delay:.5,display:'block'})
    TweenMax.to ('#theofficeplaygroundname', .5, {delay:.5, opacity:1})
    TweenMax.to ('#theofficeplaygroundname', 0, {delay:.5,display:'block'})
    TweenMax.to ('#abysmcover', .5, {delay:.5, opacity:1})
    TweenMax.to ('#abysmcover', 0, {delay:.5,display:'block'})
    TweenMax.to ('#abysmname', .5, {delay:.5, opacity:1})
    TweenMax.to ('#abysmname', 0, {delay:.5,display:'block'})
    TweenMax.to ('#homesickcover', .5, {delay:.5, opacity:1})
    TweenMax.to ('#homesickcover', 0, {delay:.5,display:'block'})
    TweenMax.to ('#homesickname', .5, {delay:.5, opacity:1})
    TweenMax.to ('#homesickname', 0, {delay:.5,display:'block'})
    TweenMax.to ('#slothcover', .5, {delay:.5, opacity:1})
    TweenMax.to ('#slothcover', 0, {delay:.5,display:'block'})
    TweenMax.to ('#slothname', .5, {delay:.5, opacity:1})
    TweenMax.to ('#slothname', 0, {delay:.5,display:'block'})
    TweenMax.to ('#shortname', .5, {delay:.5, opacity:1})
    TweenMax.to ('#shortname', 0, {delay:.5,display:'block'})
    TweenMax.to ('#shortname', .5, {delay:.5, color:'black'})
    TweenMax.to ('#projects', .5, {delay:.5, opacity:1})
    TweenMax.to ('#projects', 0, {delay:.5,display:'block'})
    TweenMax.to ('#projects', .5, {delay:.5, color:'black'})

})

document.getElementById('officecirclecolor').addEventListener('mouseover', function (){
    TweenMax.to('#officecirclecolor', .25, {scale: 1.2})
})

document.getElementById('officecirclecolor').addEventListener('mouseout', function (){
    TweenMax.to('#officecirclecolor', .25, {scale: 1})
})

document.getElementById('officecirclecolor').addEventListener('click', function (){
    TweenMax.to('#theofficeplaygroundscroll', .25, {backgroundColor:'white'})
    TweenMax.to('#prev path', .25, {fill:'black'})
    TweenMax.to('#officecirclecolor', .25, {opacity:0})
    TweenMax.to('#officecirclecolor', 0, { delay:.25, display:'none'})
    TweenMax.to('#officecirclecolor2', .25, {delay:.25, opacity:1})
    TweenMax.to('#officecirclecolor2', 0, { delay:.25, display:'block'})
    TweenMax.to('.officetext', .25, {color:'black'})
    TweenMax.to('#shortname', .25, {color:'black'})
    TweenMax.to('#projects', .25, {color:'black'})
})


document.getElementById('officecirclecolor2').addEventListener('click', function (){
    TweenMax.to('#theofficeplaygroundscroll', .25, {backgroundColor:'black'})
    TweenMax.to('#prev path', .25, {fill:'black'})
    TweenMax.to('#officecirclecolor2', .25, {opacity:0})
    TweenMax.to('#officecirclecolor2', 0, { delay:.25, display:'none'})
    TweenMax.to('#officecirclecolor', .25, {delay:.25, opacity:1})
    TweenMax.to('#officecirclecolor', 0, { delay:.25, display:'block'})
    TweenMax.to('.officetext', .25, {color:'white'})
    TweenMax.to('#shortname', .25, {color:'white'})
    TweenMax.to('#projects', .25, {color:'white'})
})

document.getElementById('officecirclecolor2').addEventListener('mouseover', function (){
    TweenMax.to('#officecirclecolor2', .25, {scale: 1.2})
})

document.getElementById('officecirclecolor2').addEventListener('mouseout', function (){
    TweenMax.to('#officecirclecolor2', .25, {scale: 1})
})

document.getElementById('cleansedcirclecolor').addEventListener('mouseover', function (){
    TweenMax.to('#cleansedcirclecolor', .25, {scale: 1.2})
})

document.getElementById('cleansedcirclecolor').addEventListener('mouseout', function (){
    TweenMax.to('#cleansedcirclecolor', .25, {scale: 1})
})

document.getElementById('cleansedcirclecolor').addEventListener('click', function (){
    TweenMax.to('#cleansedscroll', .25, {backgroundColor:'#21373D'})
    TweenMax.to('#prev path', .25, {fill:'#21373D'})
    TweenMax.to('#cleansedcirclecolor', .25, {opacity:0})
    TweenMax.to('#cleansedcirclecolor', 0, { delay:.25, display:'none'})
    TweenMax.to('#cleansedcirclecolor2', .25, {delay:.25, opacity:1})
    TweenMax.to('#cleansedcirclecolor2', 0, { delay:.25, display:'block'})
})


document.getElementById('cleansedcirclecolor2').addEventListener('click', function (){
    TweenMax.to('#cleansedscroll', .25, {backgroundColor:'black'})
    TweenMax.to('#prev path', .25, {fill:'black'})
    TweenMax.to('#cleansedcirclecolor2', .25, {opacity:0})
    TweenMax.to('#cleansedcirclecolor2', 0, { delay:.25, display:'none'})
    TweenMax.to('#cleansedcirclecolor', .25, {delay:.25, opacity:1})
    TweenMax.to('#cleansedcirclecolor', 0, { delay:.25, display:'block'})
})

document.getElementById('cleansedcirclecolor2').addEventListener('mouseover', function (){
    TweenMax.to('#cleansedcirclecolor2', .25, {scale: 1.2})
})

document.getElementById('cleansedcirclecolor2').addEventListener('mouseout', function (){
    TweenMax.to('#cleansedcirclecolor2', .25, {scale: 1})
})

document.getElementById('slothcirclecolor').addEventListener('mouseover', function (){
    TweenMax.to('#slothcirclecolor', .25, {scale: 1.2})
})

document.getElementById('slothcirclecolor').addEventListener('mouseout', function (){
    TweenMax.to('#slothcirclecolor', .25, {scale: 1})
})

document.getElementById('slothcirclecolor').addEventListener('click', function (){
    TweenMax.to('#slothscroll', .25, {backgroundColor:'#A98370'})
    TweenMax.to('#prev path', .25, {fill:'#A98370'})
    TweenMax.to('#slothcirclecolor', .25, {opacity:0})
    TweenMax.to('#slothcirclecolor', 0, { delay:.25, display:'none'})
    TweenMax.to('#slothcirclecolor2', .25, {delay:.25, opacity:1})
    TweenMax.to('#slothcirclecolor2', 0, { delay:.25, display:'block'})
})

document.getElementById('slothcirclecolor2').addEventListener('click', function (){
    TweenMax.to('#slothscroll', .25, {backgroundColor:'black'})
    TweenMax.to('#prev path', .25, {fill:'black'})
    TweenMax.to('#slothcirclecolor2', .25, {opacity:0})
    TweenMax.to('#slothcirclecolor2', 0, { delay:.25, display:'none'})
    TweenMax.to('#slothcirclecolor', .25, {delay:.25, opacity:1})
    TweenMax.to('#slothcirclecolor', 0, { delay:.25, display:'block'})
})

document.getElementById('slothcirclecolor2').addEventListener('mouseover', function (){
    TweenMax.to('#slothcirclecolor2', .25, {scale: 1.2})
})

document.getElementById('slothcirclecolor2').addEventListener('mouseout', function (){
    TweenMax.to('#slothcirclecolor2', .25, {scale: 1})
})

document.getElementById('homesickcirclecolor').addEventListener('mouseover', function (){
    TweenMax.to('#homesickcirclecolor', .25, {scale: 1.2})
})

document.getElementById('homesickcirclecolor').addEventListener('mouseout', function (){
    TweenMax.to('#homesickcirclecolor', .25, {scale: 1})
})

document.getElementById('homesickcirclecolor').addEventListener('click', function (){
    TweenMax.to('#homesickscroll', .25, {backgroundColor:'#1C4E03'})
    TweenMax.to('#prev path', .25, {fill:'#1C4E03'})
    TweenMax.to('#homesickcirclecolor', .25, {opacity:0})
    TweenMax.to('#homesickcirclecolor', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickcirclecolor2', .25, {delay:.25, opacity:1})
    TweenMax.to('#homesickcirclecolor2', 0, { delay:.25, display:'block'})
})

document.getElementById('homesickcirclecolor2').addEventListener('click', function (){
    TweenMax.to('#homesickscroll', .25, {backgroundColor:'black'})
    TweenMax.to('#prev path', .25, {fill:'black'})
    TweenMax.to('#homesickcirclecolor2', .25, {opacity:0})
    TweenMax.to('#homesickcirclecolor2', 0, { delay:.25, display:'none'})
    TweenMax.to('#homesickcirclecolor', .25, {delay:.25, opacity:1})
    TweenMax.to('#homesickcirclecolor', 0, { delay:.25, display:'block'})
})

document.getElementById('homesickcirclecolor2').addEventListener('mouseover', function (){
    TweenMax.to('#homesickcirclecolor2', .25, {scale: 1.2})
})

document.getElementById('homesickcirclecolor2').addEventListener('mouseout', function (){
    TweenMax.to('#homesickcirclecolor2', .25, {scale: 1})
})

document.getElementById('tancirclecolor').addEventListener('mouseover', function (){
    TweenMax.to('#tancirclecolor', .25, {scale: 1.2})
})

document.getElementById('tancirclecolor').addEventListener('mouseout', function (){
    TweenMax.to('#tancirclecolor', .25, {scale: 1})
})

document.getElementById('tancirclecolor').addEventListener('click', function (){
    TweenMax.to('#tanscroll', .25, {backgroundColor:'#988D05'})
    TweenMax.to('#prev path', .25, {fill:'#988D05'})
    TweenMax.to('#tancirclecolor', .25, {opacity:0})
    TweenMax.to('#tancirclecolor', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancirclecolor2', .25, {delay:.25, opacity:1})
    TweenMax.to('#tancirclecolor2', 0, { delay:.25, display:'block'})
})

document.getElementById('tancirclecolor2').addEventListener('click', function (){
    TweenMax.to('#tanscroll', .25, {backgroundColor:'black'})
    TweenMax.to('#prev path', .25, {fill:'black'})
    TweenMax.to('#tancirclecolor2', .25, {opacity:0})
    TweenMax.to('#tancirclecolor2', 0, { delay:.25, display:'none'})
    TweenMax.to('#tancirclecolor', .25, {delay:.25, opacity:1})
    TweenMax.to('#tancirclecolor', 0, { delay:.25, display:'block'})
})

document.getElementById('tancirclecolor2').addEventListener('mouseover', function (){
    TweenMax.to('#tancirclecolor2', .25, {scale: 1.2})
})

document.getElementById('tancirclecolor2').addEventListener('mouseout', function (){
    TweenMax.to('#tancirclecolor2', .25, {scale: 1})
})

document.getElementById('fakecontainer2').addEventListener('mouseover', function(){
    TweenMax.to('#abysmi2', 0, {display:'none'})
})

document.getElementById('fakecontainer2').addEventListener('mouseout', function(){
    TweenMax.to('#abysmi2', 0, {display:'block'})
})

document.getElementById('fakecontainer1').addEventListener('mouseover', function(){
    TweenMax.to('#abysmi5', 0, {display:'none'})
})

document.getElementById('fakecontainer1').addEventListener('mouseout', function(){
    TweenMax.to('#abysmi5', 0, {display:'block'})
})








document.getElementById('agt').addEventListener('click', function(){
    TweenMax.to('#rectangleagt', 1, {transformOrigin:'center' })
    TweenMax.to('#rectangleagt', 2, {scaleX: 6})
    TweenMax.to('#rectangleagt', .5, {scaleY: 15})
    TweenMax.to('.rectangles', 0, {delay: .75, display:'none'})
    TweenMax.to('#container', 0, { delay: .75, backgroundColor:'white'}) 
    TweenMax.to('#shortname', 0, {color: 'black'})
    TweenMax.to('#agt', 0 ,{ delay:1, display: 'none'})
    TweenMax.to('#agt', 1 ,{ opacity: 0})
    TweenMax.to('#apc', 1 ,{ display: 'none'})
    TweenMax.to('#glams', 1 ,{ display: 'none'})
    TweenMax.to('#film', 1 ,{ display: 'none'})
    TweenMax.to('#others', 1 ,{ display: 'none'})
    TweenMax.to('#agtscroll', 0, {delay: 1, display:'block'})
    TweenMax.to('#projects', 0, {delay: .25, display:'block'})
    TweenMax.to('#projects2', 0, {delay: .25, display:'none'})
})