document.getElementById('circle2').addEventListener('mouseover', function(){
    TweenMax.to('#circle2', 0.5, { scale: 1.3})
//     TweenMax.to('.shortname', 0, { delay: 0.2, display: 'none'})
//     TweenMax.to('.name', .4, { delay: 0.2, scaleY: '0', ease: Power4.easeOut})
//     TweenMax.to('.sections', 1.3, { delay: 0.45, scaleX: '10', ease: Power4.easeInOut})
//     TweenMax.to('.sections', 0, { delay: 1.75, width: '100vw', margin: 0, scaleX: 1})
//     TweenMax.to('#ellipse2', 0.2, { delay: 1.1, opacity: 0})
//     TweenMax.to('#ellipse3', 0.2, { delay: 1.1, opacity: 0})
//     TweenMax.to('#ellipse4', 0.2, { delay: 1.1, opacity: 0})
//     TweenMax.to('#ellipse2', 0, { delay: 1.3, display: 'none'})
//     TweenMax.to('#ellipse3', 0, { delay: 1.3, display: 'none'})
//     TweenMax.to('#ellipse4', 0, { delay: 1.3, display: 'none'})
//     TweenMax.to('#ellipse1', 0, { delay: 1.3, position: 'fixed', top: '1.35vh'})
//     TweenMax.to('.ellipse', .3, { delay: 1.4, x: '-38%', translateX: '50%'})
//     TweenMax.to('.ellipse', 0, { delay: 1.7, backgroundColor: 'white'})
//     TweenMax.to('.sections', 0.8, { delay: 1.8, scaleX: '0', ease: Power4.easeIn})
})

document.getElementById('circle2').addEventListener('mouseout', function(){
    TweenMax.to('#circle2', 0.3, { scale: 1})
})

document.getElementById('circle2').addEventListener('click', function(){
    TweenMax.to('#circle2', 1.5, { scale: 7, ease: Power3.easeOut})
    TweenMax.to('#hi', 0.25, { opacity:0})
    TweenMax.to('#hi', 0.25, { display:'none'})
    TweenMax.to('#container', 0, { delay: 0.5, backgroundColor:'black'})
    TweenMax.to('.name', 0, { delay: 2, display: 'none'})
    TweenMax.to('#projects', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#archives', 0, { delay: 0.35, display:'none'})
    // TweenMax.to('#projects', 0, { delay: 0.35, color:'white'})
    // TweenMax.to('#archives', 0, { delay: 0.35, color:'white'})
    TweenMax.to('#contact', 0, { delay: 0.35, color:'white'})
    TweenMax.to('#contact',0, {delay: .35,display:'none'})
    TweenMax.to('#contact2',0, {delay: .35, display:'block'})
    TweenMax.to('#projects2',0, {display:'block'})
    TweenMax.to('#archives2',0, {display:'block'})
    TweenMax.to('#contact2',0, {color:'white'})
    TweenMax.to('#hi2', 0, { delay: 0.1, display:'block'})
    // TweenMax.to('#contact', 0, { delay: 0.35, display: 'none'})
    TweenMax.to('#email', 0, { display:'block'})
    TweenMax.to('#contactava', 0, { delay: 0.2, display:'block'})
    TweenMax.to('#circle2', 0, {delay: 2, display: 'none'})    
    TweenMax.to('#shortname', 0, {display:'block'})
    TweenMax.to('.ellipse', 0, {display:'none'})

})

document.getElementById('contact').addEventListener('click', function(){
    TweenMax.to('#circle2', 1.5, { scale: 7, ease: Power3.easeOut})
    TweenMax.to('#hi', 0.25, { opacity:0})
    TweenMax.to('#hi', 0.25, { display:'none'})
    TweenMax.to('#circle2', 0, { delay: 1, display:'none'})
    TweenMax.to('#container', 0, { delay: 0.5, backgroundColor:'black'})
    TweenMax.to('.name', 0, { delay: 2, display: 'none'})
    TweenMax.to('#projects', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#archives', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#hi2', 0, { delay: 0.1, display:'block'})
    TweenMax.to('#email', 0, { delay: 0.1, display:'block'})
    TweenMax.to('#contactava', 1, { delay: 0.2, display:'block'})
    TweenMax.to('#circle2', 0, {delay: 1, display:'none'})
    TweenMax.to('#shortname', 0, {display:'block'})
    TweenMax.to('#shortname', 0, {color:'white'})
    TweenMax.to('.ellipse', 0, {display:'none'})
    TweenMax.to('#contact2',0, {delay: .35, display:'block'})
    TweenMax.to('#contact2',0, {color:'white'})
    TweenMax.to('#tspan', 0.3, { opacity: 0})
})

document.getElementById('shortname').addEventListener('click', function(){
    TweenMax.to('#email', 0, { delay: .5, display:'none'})
    TweenMax.to('#contactava', 0, {delay: .5, display:'none'})
    TweenMax.to('#hi2', 0, {delay: .5,display:'none'})
    TweenMax.to('#shortname', 0, {delay: .5, display:'none'})
    TweenMax.to('.projectsname', 0, {delay: .5, display:'none'})
    TweenMax.to('#circle2', 0, {scale:7})
    TweenMax.to('#container', 0, {backgroundColor:'white'})
    TweenMax.to('#circle2', 0, {display: 'block'})
    TweenMax.to('#circle2', 1, {scale:1, ease: Power3.easeIn, transform: 'translate(-50%)' })
    TweenMax.to('.name', 0, { delay: 0.5, display: 'block'})
    TweenMax.to('#projects', 0, { delay: 0.5, display:'block'})
    TweenMax.to('#projects', 0, { color:'black'})
    TweenMax.to('#projects2',0, { delay: 0.5,display:'none'})
    TweenMax.to('#archives', 0, { delay: 0.5, display:'block'})
    TweenMax.to('#archives', 0, { color:'black'})
    TweenMax.to('#archives2',0, { delay: 0.5,display:'none'})
    TweenMax.to('#contact', 0, { delay: 0.5, display:'block'})
    TweenMax.to('#contact', 0, { color:'black'})
    TweenMax.to('#contact2',0, { delay: 0.5,display:'none'})
    TweenMax.to('#hi', 0.1, {opacity: 0})
    TweenMax.to('#hi', 0, { delay: 0.5, display:'block'})
    TweenMax.to('#hi', 1, { delay:.5, opacity:1})
    TweenMax.to('.name', 1, {opacity:1})
    TweenMax.to('#circle2', 1, {opacity:1})
    TweenMax.to('#filmscroll', 0, {delay: .5, display:'none'})

})

document.getElementById('contact').addEventListener('mouseover', function(){
    TweenMax.to('#ellipse1', 0, { display:'block'})
    TweenMax.to('#ellipse1', .5, { backgroundColor:'black'})
    TweenMax.to('#contact', .5, { color:'white'})
    TweenMax.to('#contact', .2, { scale:.9})
})

document.getElementById('contact').addEventListener('mouseout', function(){
    TweenMax.to('#ellipse1', 0, { display:'none'})
    // TweenMax.to('#ellipse1', .5, { backgroundColor:'white'})
    TweenMax.to('#contact', .5, { color:'black'})
    TweenMax.to('#contact', .2, { scale:1})
})

document.getElementById('projects').addEventListener('mouseover', function(){
    TweenMax.to('#ellipse2', 0, { display:'block'})
    TweenMax.to('#ellipse2', .5, { backgroundColor:'black'})
    TweenMax.to('#projects', .5, { color:'white'})
    TweenMax.to('#projects', .2, { scale:.9})
})

document.getElementById('projects').addEventListener('mouseout', function(){
    TweenMax.to('#ellipse2', 0, { display:'none'})
    // TweenMax.to('#ellipse2', .5, { backgroundColor:'white'})
    TweenMax.to('#projects', .5, { color:'black'})
    TweenMax.to('#projects', .2, { scale:1})
})
document.getElementById('archives').addEventListener('mouseover', function(){
    TweenMax.to('#ellipse3', 0, { display:'block'})
    TweenMax.to('#ellipse3', .5, { backgroundColor:'black'})
    TweenMax.to('#archives', .5, { color:'white'})
    TweenMax.to('#archives', .2, { scale:.9})
 })
    
document.getElementById('archives').addEventListener('mouseout', function(){
    TweenMax.to('#ellipse3', 0, { display:'none'})
    // TweenMax.to('#ellipse3', .5, { backgroundColor:'white'})
    TweenMax.to('#archives', .5, { color:'black'})
    TweenMax.to('#archives', .2, { scale:1})
})

document.getElementById('projects').addEventListener('click', function(){
    TweenMax.to('#circle2', 1.5, { scale: 7, ease: Power3.easeOut})
    TweenMax.to('#hi', 0.5, { opacity:0})
    TweenMax.to('#hi', 0.5, { display:'none'})
    TweenMax.to('#circle2', 0, { delay: 1, display:'none'})
    TweenMax.to('#container', 0, { delay: 0.5, backgroundColor:'black'})
    TweenMax.to('.name', 0, { delay: 1, display: 'none'})
    TweenMax.to('#projects2', 0, { display:'block'})
    TweenMax.to('#projects2', 0, { color:'white'})
    TweenMax.to('#archives', 0, { delay: 0.35, color:'white'})
    TweenMax.to('#contact', 0, { delay: 0.35, color:'white'})
    // TweenMax.to('#contact', 0, { delay: 0.35, display: 'none'})
    TweenMax.to('#circle2', 0, {delay: 1, display: 'none'})    
    TweenMax.to('#shortname', 0, {display:'block'})
    TweenMax.to('#shortname', 0, {color:'white'})
    TweenMax.to('.projectsname', .1 ,{ display: 'block'})
    TweenMax.to('.projectsname', .1 ,{ opacity:'100'})
    TweenMax.to('#contact', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#archives', 0, { delay: 0.35, display:'none'})
    TweenMax.to('.ellipse', 0, {display:'none'})
    TweenMax.to('.rectangles', 0 ,{ display: 'block'})
    TweenMax.to('#rectangleapc', 0, {transformOrigin:'top' })
    TweenMax.to('#rectangleagt', 0, {transformOrigin:'top' })
    TweenMax.to('#rectanglefilm', 0, {transformOrigin:'top' })
    TweenMax.to('#rectangleglams', 0, {transformOrigin:'top' })
    TweenMax.to('#rectangleothers', 0, {transformOrigin:'top' })
    TweenMax.to('.slider-container', 0 ,{ delay: .25, display: 'none'})
})

document.getElementById('apc').addEventListener('mouseover', function(){
    TweenMax.to('#rectangleapc', .5, { scaleY: 1 })
    TweenMax.to('#rectangleapc', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#apc', 0, { color:'black'})
})

document.getElementById('apc').addEventListener('mouseout', function(){
    TweenMax.to('#rectangleapc', 0.5, {scaleY: 0})
    TweenMax.to('#rectangleapc', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#apc', 0, {color: 'white'})
})

document.getElementById('agt').addEventListener('mouseover', function(){
    TweenMax.to('#rectangleagt', .5, { scaleY: 1 })
    TweenMax.to('#rectangleagt', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#agt', 0, { color:'black'})
})

document.getElementById('agt').addEventListener('mouseout', function(){
    TweenMax.to('#rectangleagt', 0.5, {scaleY: 0})
    TweenMax.to('#rectangleagt', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#agt', 0, {color: 'white'})
})
document.getElementById('film').addEventListener('mouseover', function(){
    TweenMax.to('#rectanglefilm', .5, { scaleY: 1 })
    TweenMax.to('#rectanglefilm', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#film', 0, { color:'black'})
})

document.getElementById('film').addEventListener('mouseout', function(){
    TweenMax.to('#rectanglefilm', 0.5, {scaleY: 0})
    TweenMax.to('#rectanglefilm', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#film', 0, {color: 'white'})
})

document.getElementById('glams').addEventListener('mouseover', function(){
    TweenMax.to('#rectangleglams', .5, { scaleY: 1 })
    TweenMax.to('#rectangleglams', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#glams', 0, { color:'black'})
})

document.getElementById('glams').addEventListener('mouseout', function(){
    TweenMax.to('#rectangleglams', 0.5, {scaleY: 0})
    TweenMax.to('#rectangleglams', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#glams', 0, {color: 'white'})
})

document.getElementById('others').addEventListener('mouseover', function(){
    TweenMax.to('#rectangleothers', .5, { scaleY: 1 })
    TweenMax.to('#rectangleothers', 0, { delay: 0.5, transformOrigin: '0% 100%'})
    TweenMax.to('#others', 0, { color:'black'})
})

document.getElementById('others').addEventListener('mouseout', function(){
    TweenMax.to('#rectangleothers', 0.5, {scaleY: 0})
    TweenMax.to('#rectangleothers', 0, { delay: 0.5, transformOrigin: '100% 0%'})
    TweenMax.to('#others', 0, {color: 'white'})
})

document.getElementById('apc').addEventListener('click', function(){
    TweenMax.to('#rectangleapc', 1, {transformOrigin:'center' })
    TweenMax.to('#rectangleapc', 2, {scaleX: 6})
    TweenMax.to('#rectangleapc', .5, {scaleY: 15})
    TweenMax.to('.rectangles', 0, {delay: .75, display:'none'})
    TweenMax.to('#container', 0, { delay: .75, backgroundColor:'white'})  
    TweenMax.to('#shortname', 0, {color: 'black'})
    TweenMax.to('#apc', 1 ,{ display: 'none'})
    TweenMax.to('#agt', 1 ,{ display: 'none'})
    TweenMax.to('#glams', 1 ,{ display: 'none'})
    TweenMax.to('#film', 1 ,{ display: 'none'})
    TweenMax.to('#others', 1 ,{ display: 'none'})
})
document.getElementById('film').addEventListener('click', function(){
    TweenMax.to('#rectanglefilm', 1, {transformOrigin:'center' })
    TweenMax.to('#rectanglefilm', 2, {scaleX: 6})
    TweenMax.to('#rectanglefilm', .5, {scaleY: 15})
    TweenMax.to('.rectangles', 0, {delay: .75, display:'none'})
    TweenMax.to('#container', 0, { delay: .75, backgroundColor:'white'})  
    TweenMax.to('#shortname', 0, {color: 'black'})
    TweenMax.to('#apc', 1 ,{ display: 'none'})
    TweenMax.to('#agt', 1 ,{ display: 'none'})
    TweenMax.to('#glams', 1 ,{ display: 'none'})
    TweenMax.to('#film', 1 ,{ display: 'none'})
    TweenMax.to('#others', 1 ,{ display: 'none'})
    TweenMax.to('.slider-container', 0 ,{ delay: 1.5, display: 'block'})
    TweenMax.to('#filmscroll', 0, {delay: .5, display:'block'})

})

document.getElementById('archives').addEventListener('click', function(){
    TweenMax.to('#circle2', 1.5, { scale: 7, ease: Power3.easeOut})
    TweenMax.to('#hi', 0.5, { opacity:0})
    TweenMax.to('#hi', 0.5, { display:'none'})
    TweenMax.to('#circle2', 0, { delay: 1, display:'none'})
    TweenMax.to('#container', 0, { delay: 0.5, backgroundColor:'black'})
    TweenMax.to('.name', 0, { delay: 2, display: 'none'})
    TweenMax.to('#projects', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#contact', 0, { delay: 0.35, display:'none'})
    TweenMax.to('#archives2', 0, { display:'block'})
    TweenMax.to('#archives2', 0, { color:'white'})
    TweenMax.to('#circle2', 0, {delay: 1, display:'none'})
    TweenMax.to('#shortname', 0, {display:'block'})
    TweenMax.to('#shortname', 0, {color:'white'})
    TweenMax.to('.ellipse', 0, {display:'none'})
    TweenMax.to('#filmscroll', 0, {delay: 1, display:'none'})
})

